# fly.toml app configuration file generated for smartvest-w7jpuw on 2026-04-23T13:04:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smartvest-w7jpuw'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  API_PORT = '3001'
  NODE_ENV = 'production'
  PORT = '3001'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
